### ISSUE TITLE
[p2] path parameter in transformer FROM_EXCEL became sensitive to spaces

### ISSUE THREAD

**Issue by yanavera** [vividus-framework/vividus#767] opened 2020-07-24 11:15 UTC
**Describe the bug**
Transformers contains in path parameter value with spaces stopped working after update Vividus to 0.2.5 version 

**To Reproduce**
Run attached test story with example table contain transformer

**Expected behavior**
Story runs without errors and exception

**Artifacts**
test story - [test.txt](https://github.com/vividus-framework/vividus/files/4971634/test.txt)
failure trace - 
![image](https://user-images.githubusercontent.com/66370345/88385645-65de5400-cdb7-11ea-9142-3f6b70f85ca5.png)

**Execution environment (please complete the following information):**
 - Vividus version: 0.2.5
 - OS: Windows 10
 - jdk -13.0.2

**Desktop Web (if applicable, please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.61

Please, feel free to contact me if any details needed

**Comment by valfirst** [comment] 2020-07-28 10:21
The root cause is a regression issue introduced at [JBEHAVE-1411](https://jbehave.atlassian.net/browse/JBEHAVE-1411). The issue was fixed in JBehave: https://github.com/jbehave/jbehave-core/pull/291.
New version of JBehave was added to Vividus in #776.
Also the integration tests were added in #777.

**Closed by valfirst** 2020-07-28 10:21 UTC
Labels: bug, p2
