### ISSUE TITLE
Enable a possibility to add headers to UI requests

### ISSUE THREAD

**Issue by ruslan-tyshchanka** [vividus-framework/vividus#755] opened 2020-07-20 13:13 UTC
Currently there is an option to set headers for API requests, but this feature is also needed for UI requests.

At the moment this action can be performed manually through plugins, but we need to have an opportunity to use it within our autotests.

**Comment by valfirst** [comment] 2020-07-20 13:25
It looks like a duplicate of #603

**Closed** 2020-07-28 08:58 UTC
Labels: feature
