### ISSUE TITLE
Unable to create a new remote session on Sauce Labs using web/phone/iphone profile

### ISSUE THREAD

**Issue by ananyevN** [vividus-framework/vividus#945] opened 2020-09-15 13:52 UTC
**Describe the bug**
As a user, I want to test a browser application.
I want to start iPhone emulator using out of the box profile **saucelabs/web,web/phone/iphone**
But session can't correctly start because of failure "'screenshotWaitTimeout' must be of type number"
![image](https://user-images.githubusercontent.com/58809891/93218746-3b839400-f773-11ea-8de6-6e4e0b675da4.png)

**Comment by valfirst** [comment] 2021-01-06 06:21
The issue is fixed by #1279.
#1309 adds system web/tablet and web/phone tests to CI.

**Closed by valfirst** 2021-01-06 06:21 UTC
Labels: bug
