### ISSUE TITLE
MySQL data source cannot get configured

### ISSUE THREAD

**Issue by AlenaKaraliova** [vividus-framework/vividus#5486] opened 2024-11-06 08:23 UTC
**Describe the bug**
After switching from version 0.6.13 to version 0.6.14-SNAPSHOT, Vividus stopped creating data source for MySQL database connection.

**To Reproduce**
Configure MySQL database connection by providing such properties:
```
db.connection.bda.url=jdbc:mysql://localhost:3307/db_name
db.connection.bda.username=****
db.connection.bda.password=****
```
Execute step:
**When I execute SQL query `${script}` against `bda` and save result to scenario variable `result`**.

Test fails with exception (see full stacktrace below):
```
Caused by: java.lang.IllegalArgumentException: Database connection with key 'bda` and save result to scenario variable `result' is not configured in properties
```

**Expected behavior**
Expected Vividus to successfully create data source and execute the provided query.

**Execution environment**
 - Vividus version: 0.6.14-SPANSHOT
 - MySQL connector version: com.mysql:mysql-connector-j:9.1.0 (same for 0.6.13 and 0.6.14-SNAPSHOT)
 - OS: Win 11
 - Java: 17

**Full stacktrace**
```
2024-11-06 10:20:10,557 [batch-1-thread-1] INFO  org.vividus.log.LoggingStoryReporter - When I execute SQL query `${script}` against `bda` and save result to scenario variable `result` (FAILED)
(java.lang.IllegalArgumentException: Database connection with key 'bda` and save result to scenario variable `result' is not configured in properties)
2024-11-06 10:20:10,558 [batch-1-thread-1] ERROR org.vividus.log.LoggingStoryReporter - Step is failed with exception
org.jbehave.core.failures.UUIDExceptionWrapper: When I execute SQL query `<sqlQuery>` against `<dbKey>`
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:914) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.steps.StepCreator$ReportingAbstractStep.perform(StepCreator.java:639) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:379) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:397) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.vividus.steps.SubSteps.executeStep(SubSteps.java:79) ~[vividus-engine-0.6.14-SNAPSHOT.jar:0.6.14-SNAPSHOT]
	at org.vividus.steps.SubSteps.execute(SubSteps.java:60) ~[vividus-engine-0.6.14-SNAPSHOT.jar:0.6.14-SNAPSHOT]
	at org.vividus.steps.ExecutableSteps.performAllStepsIfConditionIsTrue(ExecutableSteps.java:82) ~[vividus-0.6.14-SNAPSHOT.jar:0.6.14-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:895) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.steps.StepCreator$ReportingAbstractStep.perform(StepCreator.java:639) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:379) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:397) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:397) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1442) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.lambda$performScenario$0(PerformableTree.java:1284) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableEntity.performWithStopExecutionExceptionHandling(PerformableTree.java:966) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1277) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1354) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1221) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.lambda$perform$0(PerformableTree.java:1091) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableEntity.performWithStopExecutionExceptionHandling(PerformableTree.java:966) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:1083) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:521) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:488) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:305) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:278) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: Database connection with key 'bda` and save result to scenario variable `result' is not configured in properties
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:572) ~[commons-lang3-3.17.0.jar:3.17.0]
	at org.vividus.util.property.PropertyMappedCollection.get(PropertyMappedCollection.java:54) ~[vividus-util-0.6.14-SNAPSHOT.jar:0.6.14-SNAPSHOT]
	at org.vividus.db.DataSourceManager.getDataSource(DataSourceManager.java:44) ~[vividus-plugin-db-0.6.14-SNAPSHOT.jar:0.6.14-SNAPSHOT]
	at org.vividus.db.DataSourceManager.lambda$getJdbcTemplate$0(DataSourceManager.java:38) ~[vividus-plugin-db-0.6.14-SNAPSHOT.jar:0.6.14-SNAPSHOT]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at org.vividus.db.DataSourceManager.getJdbcTemplate(DataSourceManager.java:38) ~[vividus-plugin-db-0.6.14-SNAPSHOT.jar:0.6.14-SNAPSHOT]
	at org.vividus.steps.db.DatabaseSteps.executeSql(DatabaseSteps.java:191) ~[vividus-plugin-db-0.6.14-SNAPSHOT.jar:0.6.14-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:895) ~[jbehave-core-6.0.0-alpha.4.jar:?]
	... 30 more
```

**Comment by valfirst** [comment] 2024-11-06 12:40
The issue was caused by conflicting composite steps created on user side. It's resolved by using `Priority` attribute.

**Closed by valfirst** 2024-11-06 12:40 UTC
Labels: bug, not an issue / not reproduced
